// Generated by Haxe 3.4.0
(function () { "use strict";
var Client = function() { };
Client.initInputs = function() {
	var elements = $(".form").find("input, textarea");
	elements.on("keyup blur focus",null,function(e) {
		var self = $(e.target);
		var label = self.prev("label");
		if(e.type == "keyup") {
			if(self.val() == "") {
				label.removeClass("active highlight");
			} else {
				label.addClass("active highlight");
			}
		} else if(e.type == "blur") {
			if(self.val() == "") {
				label.removeClass("active highlight");
			} else {
				label.removeClass("highlight");
			}
		} else if(e.type == "blur") {
			if(self.val() == "") {
				label.removeClass("highlight");
			} else {
				label.addClass("highlight");
			}
		}
	});
};
Client.initTabs = function() {
	$(".tab a").click(function(e) {
		e.preventDefault();
		var self = $(e.target);
		self.parent().addClass("active");
		self.parent().siblings().removeClass("active");
		var target = self.attr("href");
		$(".tab-content > div").not(target).hide();
		$(target).fadeIn(600);
	});
};
Client.onReady = function() {
	Client.initInputs();
	Client.initTabs();
};
Client.main = function() {
	$(function() {
		Client.onReady();
	});
};
Client.main();
})();
